AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FiberFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: main.zip
      Runtime: go1.x
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 3

      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any




Outputs:
  FiberApi:
    Description: Sample application for Golang API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: FiberApi


